language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode  # JRuby in 1.9 mode
  - rbx-19mode # Rubinius in 1.9 mode
matrix:
  allow_failures:
    - rvm: ruby-head

script: bundle exec rspec spec
